---
title: 'plt_restrictions check'
author: "German Villalobos"
header-includes:
  - \usepackage{bm}
  - \input{mystyles.sty}

output: pdf_document

---

Convexity-Checker

Recall that a function $f : \Real^n \mapsto \Real$ is convex if and only if $g(t) = f(x + tv)$ is convex for all $x + tv$ in dom $f$. In other words, a multivariate function is convex if and only if its univariate restrictions are convex.

The first function to go into your R package will leverage this fact to allow you to get some idea of the convexity of a multivariate function. The basic idea is that it will plot random univariate restrictions. Of course to prove convexity of a function all univariate restrictions need to be convex, and you can't plot all univariate restrictions. But if you plot several random restrictions and they all look bowl shaped, then it might be worth your time to prove the convexity of the function. Alternatively, if just one random restriction is not convex, then you know the multivariate function cannot be convex.

Using get_plot_restrictions function to verify the convexity of 9 random univariate restrictions of $f(X) = -\log \det X$ where $X$ is a positive definite $5$-by-$5$ matrix.

```{r}
library(STAT613gv6) #Load package name

fx <- function(X) {
  if (nrow(X) != ncol(X)) stop("'X' must be a square matrix")
  detX <- det(X)
  if (detX <= 0) stop("'X' must be positive definite")
  return(-log(det(X)))
}

rx <- function(n = 5, nt = 1e2) {
  ## Create positive definite X
  svdS <- svd(matrix(rnorm(n**2),n,n))
  U <- svdS$u
  X <- U %*% diag(1+rnorm(n)**2) %*% t(U)
  
  ## Create positive definite V
  svdS <- svd(matrix(rnorm(n**2),n,n))
  U <- svdS$u
  V <- U %*% diag(1+rnorm(n)**2) %*% t(U)
  
  ## Create sequence positive increasing sequence t and Z
  Z <- vector(mode="list", length=nt)
  t <- cumsum(runif(nt))
  for (i in 1:nt) {
    Z[[i]] <- X + t[i]*V
  }
  return(list(t=t, Z=Z))
}

get_plot_restrictions_fcn(fx, rx, 3, 3)# plot_restrictions(fx, rx, 3, 3) <- Uncomment this line.
```
